/**
 * AUTO-GENERATED by scripts/sprite-size-index.ts — DO NOT EDIT MANUALLY.
 * 戰場角色圖像尺寸索引「資料」（僅彙總各資料夾快取；不含任何固定邏輯）
 * Battlefield sprite size index DATA (aggregates per-folder caches; NO fixed logic).
 *
 * 各資料夾快取（.sprite-sizes.json）僅以「檔名」為鍵，並記錄尺寸變更時間戳 ts（圖檔 mtime）；
 * 此處彙總時補回資料夾前綴，還原成以完整 URL 為鍵的索引。
 * Each per-folder cache (.sprite-sizes.json) keys by FILENAME only and records a
 * size-change timestamp (ts = file mtime); this aggregator restores full-URL keys
 * by prefixing the folder path.
 *
 * 固定邏輯（型別 / 預設尺寸 / 查詢函式）位於手寫、非生成的 spriteImageSizes.ts。
 * Fixed logic (types / default / lookup) lives in the hand-written, non-generated
 * spriteImageSizes.ts.
 *
 * 重建：npm run sprite:index
 * 單檔補充：npm run sprite:index -- --append image/char/xxx.png
 *
 * 對照 PHP：CopyRow() 中 getimagesize() 讀取圖檔尺寸用於中心對齊
 * Mirrors PHP CopyRow(): getimagesize() reads size for centering.
 */
import type { ISpriteImageSize } from './spriteImageSizes';

import image_char from '../../../public/image/char/.sprite-sizes.json';
import image_char_rev from '../../../public/image/char_rev/.sprite-sizes.json';
import image_other from '../../../public/image/other/.sprite-sizes.json';

/** 圖像尺寸索引：URL → 尺寸（由各資料夾快取彙總） / Size index: URL → size (aggregated from per-folder caches) */
export const spriteImageSizes: Record<string, ISpriteImageSize> = {
  ...Object.fromEntries(Object.entries(image_char).map(([k, v]) => ["/image/char/" + k, v])),
  ...Object.fromEntries(Object.entries(image_char_rev).map(([k, v]) => ["/image/char_rev/" + k, v])),
  ...Object.fromEntries(Object.entries(image_other).map(([k, v]) => ["/image/other/" + k, v])),
};
