/**
 * AUTO-GENERATED by scripts/sprite-size-index.ts — DO NOT EDIT MANUALLY.
 * 戰場角色圖像尺寸索引（彙總各圖檔資料夾內的快取；本檔不硬編碼任何資料）
 * Battlefield sprite size index (aggregates per-folder caches; NO data hardcoded here).
 *
 * 各資料夾快取（.sprite-sizes.json）僅以「檔名」為鍵，並記錄尺寸變更時間戳 ts（圖檔 mtime）；
 * 此處彙總時補回資料夾前綴，還原成以完整 URL 為鍵的索引。
 * Each per-folder cache (.sprite-sizes.json) keys by FILENAME only and records a
 * size-change timestamp (ts = file mtime); this aggregator restores full-URL keys
 * by prefixing the folder path.
 *
 * 重建：npm run sprite:index
 * 單檔補充：npm run sprite:index -- --append image/char/xxx.png
 *
 * 對照 PHP：CopyRow() 中 getimagesize() 讀取圖檔尺寸用於中心對齊
 * Mirrors PHP CopyRow(): getimagesize() reads size for centering.
 */
export interface ISpriteImageSize {
  /** 寬度 / Width */
  width: number;
  /** 高度 / Height */
  height: number;
}

import image_char from '../../../public/image/char/.sprite-sizes.json';
import image_char_rev from '../../../public/image/char_rev/.sprite-sizes.json';
import image_other from '../../../public/image/other/.sprite-sizes.json';
import { SPRITE_DIR_PREFIX } from './spriteDirs';

/** 圖像尺寸索引：URL → 尺寸（由各資料夾快取彙總） / Size index: URL → size (aggregated from per-folder caches) */
export const spriteImageSizes: Record<string, ISpriteImageSize> = {
  ...Object.fromEntries(Object.entries(image_char).map(([k, v]) => [SPRITE_DIR_PREFIX.char + k, v])),
  ...Object.fromEntries(Object.entries(image_char_rev).map(([k, v]) => [SPRITE_DIR_PREFIX.char_rev + k, v])),
  ...Object.fromEntries(Object.entries(image_other).map(([k, v]) => [SPRITE_DIR_PREFIX.other + k, v])),
};

/** 缺漏時的預設尺寸（中心對齊用） / Default size when missing (for centering) */
export const DEFAULT_SPRITE_IMAGE_SIZE: ISpriteImageSize = { width: 100, height: 100 };

/**
 * 查詢圖像尺寸；索引缺漏時回傳預設值
 * Lookup an image size; returns the default when missing from the index.
 */
export function getSpriteImageSize(url: string): ISpriteImageSize {
  return spriteImageSizes[url] ?? DEFAULT_SPRITE_IMAGE_SIZE;
}
