/**
 * 戰場角色圖像尺寸：固定邏輯層（非生成檔）
 * Battlefield sprite image size — fixed-logic layer (NOT generated).
 *
 * 本檔為「固定邏輯」：型別定義、預設尺寸（以函式提供，避免被意外修改）、
 * 與查詢函式。實際的尺寸索引「資料」由 scripts/sprite-size-index.ts 生成為
 * spriteImageIndex.generated.ts，本檔僅 import 該資料並提供查詢介面，因此
 * 重新執行 sprite:index 時不會動到本檔。
 * This file is the "fixed logic" layer: type, a default-size factory (function form
 * so a shared constant can't be mutated), and the lookup. The actual size-index DATA
 * is generated by scripts/sprite-size-index.ts into spriteImageIndex.generated.ts;
 * this file only imports that data and exposes the lookup, so re-running sprite:index
 * never touches this file.
 */

import { spriteImageSizes } from './spriteImageIndex.generated';

/** 圖像尺寸 / Image size */
export interface ISpriteImageSize {
  /** 寬度 / Width */
  width: number;
  /** 高度 / Height */
  height: number;
}

/**
 * 缺漏時的預設尺寸（中心對齊用）
 * Default size when missing from the index (for centering).
 *
 * 以函式形式提供，每次呼叫回傳全新物件，避免呼叫端意外修改共享常數。
 * Returned as a fresh object each call so callers can't mutate a shared constant.
 */
export function getDefaultSpriteImageSize(): ISpriteImageSize {
  return { width: 100, height: 100 };
}

/**
 * 查詢圖像尺寸；索引缺漏時回傳預設值（全新物件，可安全修改）
 * Lookup an image size; returns a fresh default when missing from the index.
 *
 * @param url 圖檔 URL（如 /image/char/mon_052.png） / Image URL
 */
export function getSpriteImageSize(url: string): ISpriteImageSize {
  return spriteImageSizes[url] ?? getDefaultSpriteImageSize();
}

/** 圖像尺寸索引資料（由 spriteImageIndex.generated.ts 彙總；重新匯出供直接取用）
 *  Size-index data (aggregated in spriteImageIndex.generated.ts; re-exported for direct use) */
export { spriteImageSizes };
